### ISSUE TITLE
FFmpeg version 6.0 has been released

### ISSUE THREAD

**Issue by palenshus** [vot/ffbinaries-prebuilt#17] opened 2023-04-19 23:33 UTC
It seems this repo is a couple years behind, is this project still being supported?

https://ffmpeg.org/download.html#releases

**Comment by StefanLobbenmeier** [comment] 2023-04-20 14:30
Probably the issue is missing automation, in another issue the author said he manually aggregates the builds from various sources. Maybe it would make sense to switch to some more automatic CI like this:

https://github.com/BtbN/FFmpeg-Builds/blob/master/.github/workflows/build.yml

**Comment by StefanLobbenmeier** [comment] 2023-04-20 14:51
He mentioned his sources [here](https://github.com/ffbinaries/ffbinaries-prebuilt/issues/9#issuecomment-628262545)

MacOS source has an API: https://evermeet.cx/ffmpeg/#api
Linux source does not have an API
Windows Source server no longer exists

But Linux and Windows should be obtained from the github api of the releases here: https://github.com/BtbN/FFmpeg-Builds/releases

So it should be possible to just have a bash script call those 2 apis to aggregate a release

**Comment by palenshus** [comment] 2023-04-20 22:43
Yep, I actually worked around this yesterday by writing my own little getter. I use the https://github.com/octokit/octokit.net library to get the latest release from https://github.com/GyanD/codexffmpeg:

```cs
static async Task DownloadLatestFFmpeg()
{
    var github = new GitHubClient(new ProductHeaderValue("FFmpegDownloader"));
    var release = await github.Repository.Release.GetLatest("GyanD", "codexffmpeg");
    var asset = release.Assets.Single(r => r.Name.Contains("essentials_build.7z"));
    asset.BrowserDownloadUrl.Dump();
    using var httpClient = new HttpClient(); ;
    string path = asset.Name;
    var outputStream = File.OpenWrite(path);
    using var stream = await httpClient.GetStreamAsync(asset.BrowserDownloadUrl);
    await stream.CopyToAsync(outputStream);
}
```

**Comment by shpingalet007** [comment] 2023-06-22 14:37
Hi folks! Hello again, @vot! 👋 In context of this issue, I promote to make a GitHub Actions workflow to automatically build one time a month, for example. I would like to contribute, of course.

**Comment by vot** [comment] 2023-06-26 07:12
Hi guys, apologies for the slowness on this one.

The good news is I've started looking into GitHub actions and forked one of the repos that seemingly do it successfully. This should help with automating the builds and give us more control and transparency which is definitely a goal for this project (along with a few things like checksums to provide a greater degree of supply-chain security).

The repo in question is https://github.com/ffbinaries/ffmpeg-builds - still got to clean it up and make sure it's fit for purpose but the initial builds went reasonably well. It will ultimately replace this repo (ffbinaries-prebuilt) as the source of the builds for the ffbinaries API.
What's still left is a bit of clean up in how the builds get published + provide some extra automation for the API layer.

Unfortunately I don't have very specific timelines to provide you guys but the project is most certainly still supported and there are future plans for it (apologies for not being able to give it more hours of the day - I understand this can be frustrating).

**Comment by yuqian5** [comment] 2023-12-27 23:10
Hi @vot, I'm working on the ffmpegcore project where I am trying to add the ability to download ffmpeg binary during runtime. We want to be able to download the latest ffmpeg suite. Do you have any update on resolving this issue?

**Comment by vot** [comment] 2023-12-28 07:11
Apologies for the delay and Merry Christmas everyone!

I'm pleased to announce that **I just added the long overdue versions 5.1 and 6.1 as releases in this repo**; they're also now listed in the API.

I deliberately held back the "latest" version in the API to still point to 4.4.1 to prevent any issues. I will update the latest tag in the API in about a month or so.

You can download the new ones by explicitly naming the version.

**You can download ffmpeg 6.1 like this:**
`ffbinaries ffmpeg -v=6.1`
(or grab the URL to the zip that's right for you from `https://ffbinaries.com/api/v1/version/6.1`)

**To get the list of versions:**
`ffbinaries versions`
(or `https://ffbinaries.com/api/v1`)


@palenshus, @StefanLobbenmeier, @shpingalet007, @yuqian5 


(P.S. I still want to have the builds from that forked repo become the source of binaries and that will remain the long-term goal for this project.)

**Comment by StefanLobbenmeier** [comment] 2023-12-28 11:43
What a nice present 🎁 Merry Christmas to you as well ❤️ 

Just gave it a try with yt-dlp and worked as a drop in replacement 😄

**Closed as completed** 2024-02-03 17:50 UTC
